#
# Makefile for the input misc drivers.
#

#obj-$(CONFIG_SENSORS_STK3X1X_PIXI445CRICKET)	+= stk3x1x.o
#obj-$(CONFIG_SENSORS_LIS2DE12)  += lis2de_acc.o
#obj-$(CONFIG_SENSORS_MC3XXX)	+= mc3xxx.o
obj-$(CONFIG_SENSORS_BMA2X2_PIXI445CRICKET)	+= bstclass.o
obj-$(CONFIG_SENSORS_BMA2X2_PIXI445CRICKET)      +=  bma2x2.o
