#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-y += tct_common.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_I2C_S2333) += synaptics_dsx_i2c.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_SPI_S2333) += synaptics_dsx_spi.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI_HID_I2C_S2333) += synaptics_dsx_rmi_hid_i2c.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_CORE_S2333) += synaptics_dsx_core.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI_DEV_S2333) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_FW_UPDATE_S2333) += synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_TEST_REPORTING_S2333) += synaptics_dsx_test_reporting.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_PROXIMITY_S2333) += synaptics_dsx_proximity.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_ACTIVE_PEN_S2333) += synaptics_dsx_active_pen.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_GESTURE_S2333) += synaptics_dsx_gesture.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_VIDEO_S2333) += synaptics_dsx_video.o
