#FT6336 touchpanel driver


obj-$(CONFIG_TOUCHSCREEN_FT3307_POP445C)	+= ft6x06_ts.o
#update file
obj-$(CONFIG_TOUCHSCREEN_FT3307_POP445C)	+= ft6x06_ex_fun.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_FT3307_POP445C)	+= focaltech_ctl.o
#FACE DETECT
obj-$(CONFIG_TOUCHPANEL_PROXIMITY_SENSOR)	+= ft_psensor_drv.o
