obj-$(CONFIG_TOUCHSCREEN_GT5668) += gt1x.o
obj-$(CONFIG_TOUCHSCREEN_GT5668) += gt1x_generic.o
obj-$(CONFIG_TOUCHSCREEN_GT5668) += gt1x_tools.o
obj-$(CONFIG_TOUCHSCREEN_GT5668) += gt1x_update.o
obj-$(CONFIG_TOUCHSCREEN_GT5668) += gt1x_extents.o

