#[Feature]-BEGIN by TCTSZ.yongzhong.cheng@tcl.com,2015/8/26,for 538697:add gryoscope bmg160 driver
obj-$(CONFIG_GRYOSCOPE_BMG160)	+= bmg160.o
obj-$(CONFIG_GRYOSCOPE_BMG160)	+= bmg160_driver.o
#[Feature]-END by TCTSZ.yongzhong.cheng@tcl.com, 2015/8/26,for  538697


